[package]
name = "ping-hermano"
version = "2.0.0"
description = "PingHermano - lightweight API client"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "ping_hermano_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "multipart", "gzip", "brotli", "deflate"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
